package oauth

const (
	ColID                      = "id"
	ColStatus                  = "status"
	ColClientID                = "client_id"
	ColClientSecretHash        = "client_secret_hash"
	ColName                    = "name"
	ColRedirectURIs            = "redirect_uris"
	ColGrantTypes              = "grant_types"
	ColResponseTypes           = "response_types"
	ColScopes                  = "scopes"
	ColTokenEndpointAuthMethod = "token_endpoint_auth_method"
	ColCodeHash                = "code_hash"
	ColSubject                 = "subject"
	ColRedirectURI             = "redirect_uri"
	ColResources               = "resources"
	ColCodeChallenge           = "code_challenge"
	ColCodeChallengeMethod     = "code_challenge_method"
	ColExpiresAt               = "expires_at"
	ColConsumedAt              = "consumed_at"
	ColTokenHash               = "token_hash"
	ColFamilyID                = "family_id"
	ColParentID                = "parent_id"
	ColFamilyExpiresAt         = "family_expires_at"
	ColRevokedAt               = "revoked_at"
	ColCreatedAt               = "created_at"
	ColUpdatedAt               = "updated_at"
)
